"""empty message

Revision ID: b891000152cb
Revises: 
Create Date: 2024-07-31 20:55:11.097362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b891000152cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponcers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponcers', schema=None) as batch_op:
        batch_op.drop_column('budget')

    # ### end Alembic commands ###
