"""empty message

Revision ID: ed354307d20b
Revises: b891000152cb
Create Date: 2024-08-01 18:27:47.732535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed354307d20b'
down_revision = 'b891000152cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Integer(), nullable=True))

    with op.batch_alter_table('sponcers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Integer(), nullable=True))
        batch_op.drop_column('budget')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponcers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.INTEGER(), nullable=True))
        batch_op.drop_column('balance')

    with op.batch_alter_table('influencers', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
